Allow python 3 to pass test
Uses bc command for floating point comparison.

Checks that minimum python3 version is 3.4 and minimum python2
version is 2.7.

diff --git a/scripts/check_python b/scripts/check_python
--- a/scripts/check_python
+++ b/scripts/check_python
@@ -10,9 +10,12 @@ PYTHON="python"
 if hash "$PYTHON" 2>/dev/null; then
 	# Use full path from now on as it makes messages clearer
 	PYTHON=$(which $PYTHON)
-	PYTHON_VERSION=$($PYTHON -c 'import sys; print("%d.%d" % (sys.version_info[0], sys.version_info[1]))')
-	if [[ "$PYTHON_VERSION" != "2.7" ]]; then
-		echo "check-python: Python v2.7 not found (version reported by '$PYTHON' is $PYTHON_VERSION)." 2>&1
+	PYTHON_VERSION=$($PYTHON -c 'import sys; print("{}.{:02d}".format(sys.version_info[0], sys.version_info[1]))')
+	MINVER=2.7
+	MINVER3=3.5
+	# bc is used to do floating point comparisons
+	if [ $(bc <<< "$PYTHON_VERSION < $MINVER || ($PYTHON_VERSION > 3.0 && $PYTHON_VERSION < $MINVER3)") -eq 1 ]; then
+		echo "check-python: Python2 >= $MINVER or Python3 >= $MINVER3 not found (version reported by '$PYTHON' is $PYTHON_VERSION)." 2>&1
 		echo "check-python: Please ensure a compatible python is at the front of your PATH." 2>&1
 		exit -1
 	fi
